# Generated by Django 3.1.7 on 2021-05-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('phoneNo', models.TextField(max_length=250)),
                ('address', models.TextField(max_length=250)),
                ('cityState', models.TextField(max_length=250)),
            ],
        ),
    ]
