# Generated by Django 3.1.7 on 2021-05-16 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_dose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dose',
            name='date',
            field=models.DateField(verbose_name='dose date'),
        ),
    ]
