# Generated by Django 3.1.7 on 2021-05-16 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210516_0042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dose',
            old_name='dose',
            new_name='doseno',
        ),
    ]
