# Generated by Django 3.1.7 on 2021-05-16 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_sideeffect'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='sideeffects',
            field=models.ManyToManyField(to='main_app.SideEffect'),
        ),
    ]
