# Generated by Django 3.1.7 on 2021-05-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20210516_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='location',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
